services:
  postgres:
    image: postgres:16-alpine
    container_name: queue-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: queue_user
      POSTGRES_PASSWORD: queue_password
      POSTGRES_DB: queue_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
